### ISSUE TITLE
BUY/SELL: 422 Client Error:  for url: https://poloniex.com/tradingApi

### ISSUE THREAD

**Issue by paolinux79** [Aula13/poloniex#16] opened 2018-03-06 11:12 UTC
I am trying to place a boy or sell order but i get the exception: requests.exceptions.HTTPError: 422 Client Error:  for url: https://poloniex.com/tradingApi
Here is a code snippet:

```
defaultCurrencyPair = 'USDT_BTC'

def make_satoshi(num):
    return decimal.Decimal(num).quantize(decimal.Decimal('1.00000000'))

def test():
    available_usd = polo.returnBalances()['USDT']
    print(available_usd)
    print(make_satoshi(available_usd))
    print(make_satoshi(1))
    polo.buy(currencyPair=defaultCurrencyPair,rate=make_satoshi(1),amount=make_satoshi(available_usd))
```

**Comment by enricobacis** [comment] 2018-03-06 17:15
Does it happen even without `Decimal`? Can you try to cast your decimal to something else like a string before passing it to the api?

**Comment by timoballard** [comment] 2018-03-06 18:37
I am also encountering the 422 error. It began happening approximately 2 weeks ago; no code was changed on my end.

**Comment by enricobacis** [comment] 2018-03-06 18:47
Can you try an earlier version of the api to verify if the problem is the
api or the server itself?

**Comment by timoballard** [comment] 2018-03-06 18:51
I use the same API key with cointracking.info and everything seems to work fine there. I'm guessing that something recently changed on the Poloniex side that is causing problems with your client. I get the same error with version 0.0.13 and 0.0.15

**Comment by paolinux79** [comment] 2018-03-07 07:57
I tried using str() float() unicode() and i get always the 422.
If i try with integer .buy(currencyPair=defaultCurrencyPair,rate=1,amount=1) i obviously get a "not enough" message!

**Comment by enricobacis** [comment] 2018-03-07 12:10
I might have managed to reproduce this, but I have to check with you.

Could you please try this in your system and send me the output?

    print(Decimal("0.001"))

**Comment by paolinux79** [comment] 2018-03-07 12:56
```
>>> from decimal import Decimal
>>> print(Decimal("0.001"))
0.001
>>> 
```

**Comment by enricobacis** [comment] 2018-03-07 12:59
Can you try using the API with "0.000001"? Because I think the problem is
in the locale, the only way for me to reproduce it is to pass "0,000001"

If you don't want to buy/sell you can use the transferBalance API to move
money between exchange/margin accounts

**Comment by enricobacis** [comment] 2018-03-07 13:30
Ok, I've debugged a bit more and discovered that Poloniex changed the way to return error messages:

## Before

status code: 200
body: {"error": "........."}

## Now
status code: 422
body: {"error": "........."}

So now the error message from requests was shadowing the real error message. In version 0.0.17 this is fixed. Can you try with version 0.0.17 and post the exception that you get?

**Comment by paolinux79** [comment] 2018-03-07 13:35
polo.buy(currencyPair=defaultCurrencyPair,rate="0,000001",amount="0,000001")

  File "/usr/local/lib/python2.7/dist-packages/poloniex/poloniex.py", line 170, in _private
    response.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error:  for url: https://poloniex.com/tradingApi

**Comment by paolinux79** [comment] 2018-03-07 13:37
with 0.0.17

poland.buy(currencyPair=defaultCurrencyPair,rate="0,000001",amount="0,000001")

poloniex.exceptions.PoloniexCommandException: Invalid rate parameter.

**Comment by enricobacis** [comment] 2018-03-07 13:42
Perfect, as I expected.

Basically "0,000001" is not a valid input "0.000001" is

**Comment by paolinux79** [comment] 2018-03-07 13:45
It makes sense:

poland.buy(currencyPair=defaultCurrencyPair,rate="0.000001",amount="0.000001")

poloniex.exceptions.PoloniexCommandException: Total must be at least 1.

**Comment by enricobacis** [comment] 2018-03-07 13:46
Do you still have the problem with `Decimal`?

**Comment by paolinux79** [comment] 2018-03-07 16:36
It does not matter, I tried decimal just as a work around.

**Comment by enricobacis** [comment] 2018-03-07 16:47
So does it work now?

Please close the issue if 0.0.17 fixed the problem for you ;)

**Closed as completed** 2018-03-07 16:49 UTC
