### ISSUE TITLE
Semaphore never releases when returnTicker() is called by a daemon thread

### ISSUE THREAD

**Issue by kylegentle** [Aula13/poloniex#15] opened 2018-02-18 02:07 UTC
I'm not quite sure what's causing this, but it occurs under certain conditions when returnTicker() is called by a Process. 

Stepping through in a debugger, Semaphore typically releases after leaving this `with` statement: https://github.com/Aula13/poloniex/blob/c6aec1f722e237fbbfcbc665d70e5fe36102563f/poloniex/concurrency.py#L68

However, when returnTicker() is called by a Poloniex class instance whose RecurrentTimer is a daemon thread, Semaphore never releases, and the program stalls after 6 calls to returnTicker(). I've attached two files with results from printing the `__dict__ `of a Poloniex class instance at the time of calling returnTicker(), for comparison.

Please let me know if I can provide any further information; I'm a bit out of my depth here!

[instance.txt](https://github.com/Aula13/poloniex/files/1734337/instance.txt)
[instance_with_daemon_timer.txt](https://github.com/Aula13/poloniex/files/1734338/instance_with_daemon_timer.txt)

**Comment by topher23** [comment] 2018-02-18 02:19
Also seeing this issue.

**Comment by topher23** [comment] 2018-02-24 06:01
Bump on this

**Comment by topher23** [comment] 2018-02-25 00:12
We could not figure out this issue. It seems that it has to do with the fact that you are packaging your own concurrency engine with this lib. As a result, we have decided to move forward with this library instead: https://github.com/s4w3d0ff/python-poloniex . We will keep an eye on this issue to see if it gains traction. 

Thanks

**Comment by enricobacis** [comment] 2018-02-26 18:20
@topher23 @kylegentle, I just fixed something similar for issue #14 . Could you check if the current code still gives you the error? The fact is that you should delete the object after using it since __del__ is in charge of destroying the Timer object, which otherwise has the lock on the object.

If that's the case we can further study together a better approach, otherwise please add a minimal example of code to reproduce the behaviour.

**Comment by enricobacis** [comment] 2018-03-09 10:57
@topher23 @kylegentle any update?

**Comment by enricobacis** [comment] 2018-04-13 08:32
I'm closing this due to no updates. Please re-open this issue if the problem arises again.

**Closed as completed by enricobacis** 2018-04-13 08:32 UTC

**Comment by kylegentle** [comment] 2018-05-01 01:08
Hi @enricobacis, I can confirm that the issue persists. I apologize for the long delay in this update; it's been a hectic couple of months. If you're interested in fixing this, I'm happy to provide any additional info that might be useful to you.
